### PR TITLE
Adjustments related to the direct RPC gathering of blocks.

### PR DESCRIPTION
**Pull request by rylaix**

### CODE REVIEW

**Review by fleupold — APPROVED** [review]

**Comment by rylaix** [comment]
Merged to main

**Comment by rylaix** [comment]
Hey, @fleupold. Already started pushing to public Milestone 2 Phases. Is there any additions you want to add to the Milestone 2 specifically or for the project itself?

**Comment by fleupold** [comment]
Sounds good! The main deliverable of milestone 2 should be a service that is able to identify and quantify violation of the the "optimal bundle merging rule" from https://docs.cow.fi/mevblocker/builders/rules.

> For example, suppose a builder included only one bundle when it was possible to include two bundles for the same transaction, hence failing to maximize the refund. Such a builder may be asked to pay as damage the reward from the missing bundle (plus the reconnection fee).

This will require simulation of blocks with MEVBlocker transactions in different compositions. Let's say a block was
1. tx1
2. mevblocker_target_tx
3. backrun_tx
4. refund
5. another tx

But there were many backruns submitted, we need to also check if blocks such as 

1. tx1
2. mevblocker_target_tx
3. other_backrun_tx(s) (all greedly possible permutations of backruns that were submitted before x seconds into the block)

and check for the ones that simulate successfully if they would have given the user/builder more value (this would be a violation).

Here is an example of a transaction that didn't receive the highest possible backrun: https://etherscan.io/tx/0xd789449863d0f153aea81c46829e082728d000f145a310612fcdd7c5cfcb6f86

**Comment by rylaix** [comment]
Your additions sounds good! Will include it.
I don't want to rush things, but if milestone 1 is completed, when will I receive the payment for it?

**Comment by fleupold** [comment]
> I don't want to rush things, but if milestone 1 is completed, when will I receive the payment for it?

Can you please contact the grants committee for this? I've let them know that milestone 1 is considered ✅

**Comment by rylaix** [comment]
> Can you please contact the grants committee for this?

Wrote on the forum👌

**Pull request merged**
